name: MyProccess

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Create build folder
        run: mkdir build
        
      - name: Build Project With Cmake
        run: |
          cd build
          cmake ..
          cmake --build .
      
          
      - name: Show Files
        run: ls -a
        
  withdocker:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Build With Docker
        run: docker build -t mydocker .
          
